### ISSUE TITLE
Auto Upgrades

### ISSUE THREAD

**Issue by lkellar** [puffyboa/fidget-widget#1]
I love the game, but whenever you hover over the upgrade button and you have enough rotations, it automatically upgrades. This is an issue because some of us want to enjoy the green environmental fidget spinner longer and while spinning, it's hard to not hover over the button. Thanks!

**Comment by jpsank** [comment]
The upgrade button was being triggered when the mouse was pressed over it, which caused your accidental upgrading issue. I fixed it so it triggers when the mouse is released over it.
